/**
 * A class that contains properties necessary to perform Encrypt
 * @param {EncryptDetails} encryptDetails An instance of {@link EncryptDetails}
 * @param {string} [opcRequestId] Unique identifier for the request. If provided, the returned request ID will include this value. Otherwise, a random request ID will be generated by the service.
 * @class EncryptRequest
 */
class EncryptRequest {

	constructor(encryptDetails, opcRequestId){
		this._headers = {};
		this._pathParams = {};
		this._queryParams = {};
		this.body = '';
		this.body = encryptDetails;
		this.encryptDetails = encryptDetails;
		this.opcRequestId = opcRequestId;
	}

	get headers(){
		this._headers['opc-request-id'] = this.opcRequestId;
		return this._headers;
	}
	set headers(value){
		this._headers = value;
	}
	get queryParams(){
		return this._queryParams;
	}
	set queryParams(value){
		this._queryParams = value;
	}
	get pathParams(){
		return this._pathParams;
	}
	set pathParams(value){
		this._pathParams = value;
	}
}
module.exports = EncryptRequest;