/**
 * A class that contains properties necessary to perform GenerateDataEncryptionKey
 * @param {GenerateDataEncryptionKeyDetails} generateDataEncryptionKeyDetails An instance of {@link GenerateDataEncryptionKeyDetails}
 * @param {string} [opcRequestId] Unique identifier for the request. If provided, the returned request ID will include this value. Otherwise, a random request ID will be generated by the service.
 * @class GenerateDataEncryptionKeyRequest
 */
class GenerateDataEncryptionKeyRequest {

	constructor(generateDataEncryptionKeyDetails, opcRequestId){
		this._headers = {};
		this._pathParams = {};
		this._queryParams = {};
		this.body = '';
		this.body = generateDataEncryptionKeyDetails;
		this.generateDataEncryptionKeyDetails = generateDataEncryptionKeyDetails;
		this.opcRequestId = opcRequestId;
	}

	get headers(){
		this._headers['opc-request-id'] = this.opcRequestId;
		return this._headers;
	}
	set headers(value){
		this._headers = value;
	}
	get queryParams(){
		return this._queryParams;
	}
	set queryParams(value){
		this._queryParams = value;
	}
	get pathParams(){
		return this._pathParams;
	}
	set pathParams(value){
		this._pathParams = value;
	}
}
module.exports = GenerateDataEncryptionKeyRequest;