/**
 * A class that contains properties necessary to perform GetKey
 * @param {string} keyId Minimum: 1 Maximum: 255 The OCID of the key.
 * @param {string} [opcRequestId] Unique identifier for the request. If provided, the returned request ID will include this value. Otherwise, a random request ID will be generated by the service.
 * @class GetKeyRequest
 */
class GetKeyRequest {

	constructor(keyId, opcRequestId){
		this._headers = {};
		this._pathParams = {};
		this._queryParams = {};
		this.body = '';
		this.keyId = keyId;
		this.opcRequestId = opcRequestId;
	}

	get headers(){
		this._headers['opc-request-id'] = this.opcRequestId;
		return this._headers;
	}
	set headers(value){
		this._headers = value;
	}
	get queryParams(){
		return this._queryParams;
	}
	set queryParams(value){
		this._queryParams = value;
	}
	get pathParams(){
		this._pathParams['keyId'] = this.keyId;
		return this._pathParams;
	}
	set pathParams(value){
		this._pathParams = value;
	}
}
module.exports = GetKeyRequest;